### ISSUE TITLE
Improper Electron Security Practices

### ISSUE THREAD

**Issue by night** [leovoel/BeautifulDiscord#94]
Upon reviewing this project's injection code, it appears it disables numerous security features implemented by Discord to ensure remote code is sufficiently sandboxed from the operating system. As it stands, this software is a walking remote code execution waiting to happen.

1. Node Integration Enabled

```python
to_write = to_write.replace(b'nodeIntegration: false', b'nodeIntegration: true', 1)
```

This software leaks node integration into the main window. This means the window has access to directly modify the file system and execute arbitrary commands.

2. Content Security Policy (CSP) Disabled

```javascript
    bypass_csp = textwrap.dedent("""
    require("electron").session.defaultSession.webRequest.onHeadersReceived(({ responseHeaders }, done) => {
      Object.keys(responseHeaders)
      .filter(k => (/^content-security-policy/i).test(k) || (/^x-frame-options/i).test(k))
      .map(k => (delete responseHeaders[k]));
      done({ responseHeaders });
    });
    """)
```

CSP exists to mitigate and prevent attacks around most XSS and content injection. If someone finds XSS in Discord, node integration being enabled would directly result in remote code execution.

Security of Electron is not to be taken lightly as there are many foot-guns. By releasing software like this and encouraging people to install it, you are putting users at risk without taking proper steps to keep Electron secure. I would strongly encourage you to read up on the best security practices for Electron at https://www.electronjs.org/docs/tutorial/security and apply those to this project.

**Comment by Inve1951** [comment]
FYI
first discussion: https://github.com/rauenzi/BetterDiscordApp/issues/442
third discussion: https://github.com/joe27g/EnhancedDiscord/issues/143

**Comment by Rapptz** [comment]
The nodeIntegration could probably be removed since I already use context bridge to play "nice" with the current system. However I can't remove the code that removes the CSP headers since there is a large theming community that relies on loading stylesheets from the internet.

**Comment by night** [comment]
> However I can't remove the code that removes the CSP headers since there is a large theming community that relies on loading stylesheets from the internet.

Rather than removing CSP entirely, perhaps an appropriate change could be to extend the CSP to include the changes your client mod needs to function. This ensures CSP is still able to provide value outside of styles.

**Comment by Rapptz** [comment]
> Rather than removing CSP entirely, perhaps an appropriate change could be to extend the CSP to include the changes your client mod needs to function. This ensures CSP is still able to provide value outside of styles.

The history of this project has tried however changes to the CSP headers has broken it historically:

Originally they were bypassed through this old API (https://github.com/leovoel/BeautifulDiscord/commit/d38b3833dab7798614c8f0bef598525643457401), then we changed it to play mostly nice by just replacing the header (https://github.com/leovoel/BeautifulDiscord/commit/1848f2a244a75c13549af61393b278322e8d47ea), then it was changed to modify instead of replace since it broke the app (https://github.com/leovoel/BeautifulDiscord/commit/64d8eca655b4476918addeacfb9b7a1443e87bc6). It was changed to allow stylesheets since it wasn't working still around here (https://github.com/leovoel/BeautifulDiscord/commit/c4fe01779d2bbcb4b9d2d70b765d827447e5bdc6). When it still wasn't working or playing nice with `@import` it was removed entirely (https://github.com/leovoel/BeautifulDiscord/commit/bb8a843721109b7faccdf4e544b58b60016e289d).

Anyway I did find the CSP headers Discord uses and I found the discrepancy between the original replacement and the new one.

nodeIntegration has been left alone here: https://github.com/leovoel/BeautifulDiscord/commit/57b11b32d1d228e92f7917ed4b2176e8227691f0
CSP headers are playing nicely here: https://github.com/leovoel/BeautifulDiscord/commit/44ea225bee249ab63e93d68ee1ef8d09d1c29860
